name: grocery
description: "A new Flutter project."

# The following line prevents accidental publishing to pub.dev.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev.

# Version and build number.
version: 1.0.0+1

# Environment configuration.
environment:
  sdk: ">=3.7.0 <4.0.0"

# Dependencies required for the project.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.12
  get_storage: ^2.1.1
  url_launcher: ^6.3.1
  another_flutter_splash_screen: ^1.2.1
  google_nav_bar: ^5.0.7
  gap: ^3.0.1
  logger: ^2.5.0
  shimmer: ^3.0.0
  flutter_shimmer: ^2.1.2

# Development dependencies.
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

# Flutter-specific configuration.
flutter:
  uses-material-design: true

  assets:
    - assets/

# Flutter launcher icons configuration.
flutter_icons:
  android: true
  ios: true
  image_path: "assets/f.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/f.png"
  app_name: "FramIn"

# flutter pub run flutter_launcher_icons
